/*
    <INDEX>
*/
SELECT ROWID, 
       EMP_ID, 
       EMP_NAME
FROM EMPLOYEE;

SELECT ROWID,
      DEPT_ID
FROM DEPARTMENT;


SELECT * 
FROM EMPLOYEE
WHERE EMP_ID = 202;

SELECT * 
FROM TB_STUDENT
--WHERE STUDENT_NAME = '황효종';
WHERE STUDENT_NO = 'A511332';

-- 키 값(STUDENT_NAME)에 이미 중복된 값이 있기 때문에 오류 발생 <duplicate keys found>
CREATE UNIQUE INDEX IDX_STUDENT_NAME
ON TB_STUDENT(STUDENT_NAME);

-- 비고유 인덱스 생성 ---------------------------------깃 확인하기
CREATE INDEX IDX_STUDENT_NAME
ON TB_STUDENT(STUDENT_NAME);

-- 결합인덱스 생성
-- A617031   C2272800
SELECT *
FROM TB_GRADE
WHERE STUDENT_NO = 'A617031' AND CLASS_NO = 'C2272800';


CREATE INDEX IDX_STUDENT_CLASS_NO
ON TB_GRADE(STUDENT_NO, CLASS_NO);

-- INDEX 삭제
DROP INDEX IDX_STUDENT_NAME;

